columns:
  - name: name
    provider: name
  - name: address
    provider: address
    replace_newlines: true
  - name: email
    provider: email
  - name: phone_number
    provider: phone_number
  - name: job
    provider: job
  - name: company
    provider: company
  - name: birthdate
    provider: date_of_birth
    as_iso: true
  - name: credit_card
    provider:
      number: credit_card_number
      provider: credit_card_provider
      expiration_date: credit_card_expire
  - name: ssn
    provider: ssn
